Prj 402
IMIO/imio.project.core pull request #3
Opened 2020-04-24 08:21 UTC by fngaha

2020-04-28 07:16 UTC, sgeulette commented on src/imio/project/core/utils.py
> +        return api.content.find(object_provides=IProjectSpace)[0].getObject()
avec object_provides dans une query, je te conseille de toujours utiliser IProjectSpace.__identifier__ car c'est uniquement ce qui fonctionne si tu utilises portal_catalog. Ici c'est plone.api qui transforme cela si on lui passe uniquement l'interface

2020-04-28 07:16 UTC, sgeulette commented on src/imio/project/core/utils.py
> +    while parent.portal_type != 'Plone Site' and not IProjectSpace.providedBy(parent):
inverse le test car on aura en général toujours le projectspace avant le site plone

2020-05-06 06:54 UTC, sgeulette requested changes

2020-05-06 06:54 UTC, sgeulette commented on src/imio/project/core/browser/views.py
> +        manage_fields(self, self.context, 'add')
dans le cas du add, le self.context est le parent ! Cela ne fonctionnera pas ! il faut garder le portal_type comme avant et utiliser dans la méthode manage_fields le the_form.context comme contexte. Teste cela en ajoutant un OS: ça devrait se planter !

2020-05-06 06:54 UTC, sgeulette commented on src/imio/project/core/browser/views.py
> +def manage_fields(the_form, context, mode):
ne pas changer: voir le commentaire suivant

2020-05-07 14:53 UTC, fngaha commented on src/imio/project/core/browser/views.py
> +        manage_fields(self, self.context, 'add')
J'ai vais justement un doute sur le AddForm, et en effet ça se plante dans ce cas.
J'ai remis le portal_type en paramètre et utilisé the_form

2020-05-08 07:09 UTC, sgeulette approved these changes

2020-06-15 06:47 UTC, sgeulette requested changes

2020-06-15 06:47 UTC, sgeulette commented on src/imio/project/core/events.py
> +        #Update customViewFields defined on DashboardCollection
C'est propre au pst: il faudrait donc le mettre dans un event lié à pstprojectspace et dans le package pst

2020-06-15 06:47 UTC, sgeulette commented on src/imio/project/core/events.py
> +            if 'strategicobjective_columns' in attr:
si tu nommes les champs en commencant par le nom du dossier, tu peux éviter de répéter du code:
si attr finis par columns, tu prends le début et tu as le nom du dossier. tu fais ta recherche et tu mets à jour...

2020-06-15 06:47 UTC, sgeulette commented on src/imio/project/core/events.py
> +                ps_path = '/'.join(obj.getPhysicalPath()) + '/pstsubactions'
ce chemin n'existe pas, les sousactions sont utilisent les recherches actions

2020-06-15 12:22 UTC, fngaha commented on src/imio/project/core/events.py
> +        #Update customViewFields defined on DashboardCollection
Ok très bien

2020-06-15 12:23 UTC, fngaha commented on src/imio/project/core/events.py
> +            if 'strategicobjective_columns' in attr:
Je me doutais bien que c'était perfectible, voilà

2020-06-15 12:23 UTC, fngaha commented on src/imio/project/core/events.py
> +                ps_path = '/'.join(obj.getPhysicalPath()) + '/pstsubactions'
Claire

2020-06-24 06:45 UTC, sgeulette approved these changes

2020-06-24 06:45 UTC, merged